CREATE TABLE bookmarks (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	title text not null,
	description text, 
	url text not null, 
	rating integer check (rating > 0) check (rating < 6)
);
